version: "3.8"

services:
  buddy:
    build:
      dockerfile: ./docker/Python
    container_name: buddy_app
    volumes:
      - ./files:/app/files
      - ./outputs:/app/outputs
      - ./cache:/app/cache
      - ./generated:/app/generated
    depends_on:
      - ollama
      - postgres
    environment:
      - OLLAMA_URL=http://ollama:11434
      - TOKENIZERS_PARALLELISM=false
    networks:
      - buddy_ollama_network
      - postgres_network

  ollama:
    build:
      dockerfile: ./docker/Ollama
    container_name: ollama_container
    ports:
      - "11434:11434"
    networks:
      - buddy_ollama_network

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${database}
    ports:
      - "${port}:${port}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  buddy_ollama_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  pgdata:
